export default {
  products: [
    {
      _id: "1",
      typeProduct: "Laptop Gaming",
      factory: "MSI",
      name: "Laptop Gaming MSI GL65 Leopard 10SEK 235VN (per-key rgb)",
      cpu: "Intel Core i7-10750H 2.6GHz up to 5.0GHz 12MB",
      gpu: "NVIDIA GeForce RTX 2060 6GB GDDR6",
      ram: "16GB DDR4 2666MHz",
      image: "/img/products/msi1.jpg",
      harddrive: "1TB SSD M.2 PCIE, x1 slot 2.5inch SATA (HDD/SSD)",
      screen:
        "15.6inch FHD (1920 x 1080) IPS with Anti-Glare, 144Hz, Thin Bezel, 100% sRGB",
      io:
        "1x Type-C USB3.2 Gen2, 3x Type-A USB3.2 Gen1, 1x Mini-DisplayPort, 1x (4K @ 30Hz) HDMI, 1x RJ45",
      audio: "Nahimic 3 Audio Technology",
      keyboard: "Per-Key RGB",
      lan: "Killer Gb LAN",
      wifi: "Intel Wi-Fi 6 AX201(2*2 ax)",
      bluetooth: "v5.1",
      webcam: "HD type (30fps@720p)",
      os: "Windows 10 Home",
      pin: "6 Cell 51WHr",
      weight: "2.3 kg",
      color: "Đen",
      price: 1700,
      size: "357.7 x 248 x 27.5 mm",
      sdslot: "SD (XC/HC) Card Reader",
      countInStock: 6,
      description:
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro corrupti facere beatae, earum incidunt eos labore amet dicta nostrum saepe aliquam? Velit cumque esse cum officia asperiores dolorem temporibus perferendis?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro corrupti facere beatae, earum incidunt eos labore amet dicta nostrum saepe aliquam? Velit cumque esse cum officia asperiores dolorem temporibus perferendis?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro corrupti facere beatae, earum incidunt eos labore amet dicta nostrum saepe aliquam? Velit cumque esse cum officia asperiores dolorem temporibus perferendis?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro corrupti facere beatae, earum incidunt eos labore amet dicta nostrum saepe aliquam? Velit cumque esse cum officia asperiores dolorem temporibus perferendis?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro corrupti facere beatae, earum incidunt eos labore amet dicta nostrum saepe aliquam? Velit cumque esse cum officia asperiores dolorem temporibus perferendis?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro corrupti facere beatae, earum incidunt eos labore amet dicta nostrum saepe aliquam? Velit cumque esse cum officia asperiores dolorem temporibus perferendis?",
    },
    {
      _id: "2",
      typeProduct: "Laptop Gaming",
      factory: "ASUS",
      name: "Laptop Gaming Asus ROG STRIX G G531 VAL319T",
      cpu: "Intel Core I7-9750H 2.6GHz Up To 4.5GHz 12MB",
      gpu: "NVIDIA GeForce RTX 2060 6GB GDDR6",
      ram: "16GB DDR4 2666MHz",
      image: "/img/products/asus10.jpg",
      harddrive: "	512GB SSD PCIE G3X4",
      screen: "	15.6inch FHD (1920 x 1080) IPS, 120Hz, Wide View, Narrow Bezel",
      io: "3x USB 3.1, 1x Type C USB 3.1 (Gen 2), HDMI, RJ-45",
      audio: "	ASUS Sonic Studio",
      keyboard: "ím	4 Zone KB",
      lan: "AN	10/100/1000 Base T",
      wifi: "802.11 AC (2x2)",
      bluetooth: "v5.0",
      webcam: "None",
      os: "Windows 10 Home",
      pin: "4 Cell 66WHrs",
      weight: "2.4 kg",
      color: "	Black",
      price: 1400,
      size: "36 x 27.5 x 2.58 ~ 2.58 (cm)",
      sdslot: "empty",
      countInStock: 5,
      description:
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro corrupti facere beatae, earum incidunt eos labore amet dicta nostrum saepe aliquam? Velit cumque esse cum officia asperiores dolorem temporibus perferendis?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro corrupti facere beatae, earum incidunt eos labore amet dicta nostrum saepe aliquam? Velit cumque esse cum officia asperiores dolorem temporibus perferendis?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro corrupti facere beatae, earum incidunt eos labore amet dicta nostrum saepe aliquam? Velit cumque esse cum officia asperiores dolorem temporibus perferendis?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro corrupti facere beatae, earum incidunt eos labore amet dicta nostrum saepe aliquam? Velit cumque esse cum officia asperiores dolorem temporibus perferendis?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro corrupti facere beatae, earum incidunt eos labore amet dicta nostrum saepe aliquam? Velit cumque esse cum officia asperiores dolorem temporibus perferendis?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro corrupti facere beatae, earum incidunt eos labore amet dicta nostrum saepe aliquam? Velit cumque esse cum officia asperiores dolorem temporibus perferendis?",
    },
    {
      _id: "3",
      typeProduct: "Laptop Gaming",
      factory: "MSI",
      name: "Laptop Gaming MSI GL65 Leopard 10SEK 235VN (per-key rgb)",
      cpu: "Intel Core i7-10750H 2.6GHz up to 5.0GHz 12MB",
      gpu: "NVIDIA GeForce RTX 2060 6GB GDDR6",
      ram: "16GB DDR4 2666MHz",
      image: "/img/products/msi1.jpg",
      harddrive: "	1TB SSD M.2 PCIE, x1 slot 2.5inch SATA (HDD/SSD)",
      screen:
        "15.6inch FHD (1920 x 1080) IPS with Anti-Glare, 144Hz, Thin Bezel, 100% sRGB",
      io:
        "1x Type-C USB3.2 Gen2, 3x Type-A USB3.2 Gen1, 1x Mini-DisplayPort, 1x (4K @ 30Hz) HDMI, 1x RJ45",
      audio: "Nahimic 3 Audio Technology",
      keyboard: "Per-Key RGB",
      lan: "Killer Gb LAN",
      wifi: "Intel Wi-Fi 6 AX201(2*2 ax)",
      bluetooth: "v5.1",
      webcam: "HD type (30fps@720p)",
      os: "Windows 10 Home",
      pin: "6 Cell 51WHr",
      weight: "2.3 kg",
      color: "Đen",
      price: 1700,
      size: "357.7 x 248 x 27.5 mm",
      sdslot: "SD (XC/HC) Card Reader",
      countInStock: 4,
      description:
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro corrupti facere beatae, earum incidunt eos labore amet dicta nostrum saepe aliquam? Velit cumque esse cum officia asperiores dolorem temporibus perferendis?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro corrupti facere beatae, earum incidunt eos labore amet dicta nostrum saepe aliquam? Velit cumque esse cum officia asperiores dolorem temporibus perferendis?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro corrupti facere beatae, earum incidunt eos labore amet dicta nostrum saepe aliquam? Velit cumque esse cum officia asperiores dolorem temporibus perferendis?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro corrupti facere beatae, earum incidunt eos labore amet dicta nostrum saepe aliquam? Velit cumque esse cum officia asperiores dolorem temporibus perferendis?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro corrupti facere beatae, earum incidunt eos labore amet dicta nostrum saepe aliquam? Velit cumque esse cum officia asperiores dolorem temporibus perferendis?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro corrupti facere beatae, earum incidunt eos labore amet dicta nostrum saepe aliquam? Velit cumque esse cum officia asperiores dolorem temporibus perferendis?",
    },
    {
      _id: "4",
      typeProduct: "Laptop Gaming",
      factory: "MSI",
      name: "Laptop Gaming MSI GL65 Leopard 10SEK 235VN (per-key rgb)",
      cpu: "Intel Core i7-10750H 2.6GHz up to 5.0GHz 12MB",
      gpu: "NVIDIA GeForce RTX 2060 6GB GDDR6",
      ram: "16GB DDR4 2666MHz",
      image: "/img/products/msi1.jpg",
      harddrive: "	1TB SSD M.2 PCIE, x1 slot 2.5inch SATA (HDD/SSD)",
      screen:
        "15.6inch FHD (1920 x 1080) IPS with Anti-Glare, 144Hz, Thin Bezel, 100% sRGB",
      io:
        "1x Type-C USB3.2 Gen2, 3x Type-A USB3.2 Gen1, 1x Mini-DisplayPort, 1x (4K @ 30Hz) HDMI, 1x RJ45",
      audio: "Nahimic 3 Audio Technology",
      keyboard: "Per-Key RGB",
      lan: "Killer Gb LAN",
      wifi: "Intel Wi-Fi 6 AX201(2*2 ax)",
      bluetooth: "v5.1",
      webcam: "HD type (30fps@720p)",
      os: "Windows 10 Home",
      pin: "6 Cell 51WHr",
      weight: "2.3 kg",
      color: "Đen",
      price: 1700,
      size: "357.7 x 248 x 27.5 mm",
      sdslot: "SD (XC/HC) Card Reader",
      countInStock: 10,
      description:
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro corrupti facere beatae, earum incidunt eos labore amet dicta nostrum saepe aliquam? Velit cumque esse cum officia asperiores dolorem temporibus perferendis?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro corrupti facere beatae, earum incidunt eos labore amet dicta nostrum saepe aliquam? Velit cumque esse cum officia asperiores dolorem temporibus perferendis?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro corrupti facere beatae, earum incidunt eos labore amet dicta nostrum saepe aliquam? Velit cumque esse cum officia asperiores dolorem temporibus perferendis?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro corrupti facere beatae, earum incidunt eos labore amet dicta nostrum saepe aliquam? Velit cumque esse cum officia asperiores dolorem temporibus perferendis?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro corrupti facere beatae, earum incidunt eos labore amet dicta nostrum saepe aliquam? Velit cumque esse cum officia asperiores dolorem temporibus perferendis?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro corrupti facere beatae, earum incidunt eos labore amet dicta nostrum saepe aliquam? Velit cumque esse cum officia asperiores dolorem temporibus perferendis?",
    },
  ],
};
